"""add playlist heaps

Revision ID: 85e46633ef5f
Revises: e1219421068b
Create Date: 2022-02-21 16:47:44.753623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e46633ef5f'
down_revision = 'e1219421068b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_types_id'), 'playlist_types', ['id'], unique=False)
    op.create_table('playlist_heaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['playlist_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_heaps_id'), 'playlist_heaps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_heaps_id'), table_name='playlist_heaps')
    op.drop_table('playlist_heaps')
    op.drop_index(op.f('ix_playlist_types_id'), table_name='playlist_types')
    op.drop_table('playlist_types')
    # ### end Alembic commands ###
